site_name: Fohdeesha Docs
theme:
  name: 'material'
  palette:
    primary: 'deep orange'
    accent: 'blue'

dev_addr: 192.168.1.8:8000
nav:
    - Home: index.md
    - Brocade:
        - 'FCX / ICX6610': 'fcx.md'
        - 'ICX6430 / ICX6450': 'icx64xx.md'
        - 'ICX6650': 'icx6650.md'
        - 'ICX7150': 'icx7150.md'
        - 'ICX7250 / ICX7450': 'icx7250.md'
        - 'JTAG LB6M': 'jtag.md'
        - 'JTAG ICX6610': 'jtag6610.md'
        - 'Hidden Dev Stuff': `hidden.md`
        - 'Accessing Linux': `linux.md`
        - 'Extracting Firmware': `firmware.md`
        - 'Extracting Licenses': `extract.md`
        - 'ICX6610 Stack Ports': `stack-ports.md`
        - 'EEPROM Unlocks': `eeprom.md`
    - Other:
        - 'Multiple /64s *nix': '64nix.md'
