site_name: Fohdeesha Docs
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'red'

dev_addr: 192.168.1.8:8000
nav:
    - Home: index.md
    - Brocade:
        - 'FCX / ICX6610': 'fcx.md'
        - 'ICX6430 / ICX6450': 'icx64xx.md'
        - 'ICX6650': 'icx6650.md'
        - 'ICX7150': 'icx7150.md'
        - 'ICX7250': 'icx7250.md'
        - 'JTAG Recovery': 'jtag.md'

